# Generated by Django 6.1.1 on 2026-09-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('url', models.URLField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
