# Generated by Django 6.1.1 on 2026-09-29 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('recomendacion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='citas.cita')),
            ],
        ),
    ]
